version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv --link-mode copy run python -m sphinx docs/source $READTHEDOCS_OUTPUT/html -b html -W

sphinx:
  configuration: docs/source/conf.py