version: 2

build:
  os: "ubuntu-24.02"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv run python -m sphinx docs $READTHEDOCS_OUTPUT/html -b html -W

sphinx:
  configuration: docs/source/conf.py