name: Build and publish

on: [push, pull_request]

jobs:
  build_wheel:
    name: Build wheel

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install wheel

      - name: Build wheel
        run: python setup.py bdist_wheel --universal

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: ./dist/*.whl

  check_wheel:
    name: Check wheel

    needs: [build_wheel]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install twine

      - name: Download wheel
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Test the wheel
        run: |
          find ./dist/*.whl -maxdepth 1 -type f | xargs python -m pip install
          cd ..
          python -c "import minigun, sys; print(minigun.__version__); sys.exit(0)"

      - name: Check README rendering for PyPI
        run: twine check dist/*

  test_publish:
    name: Test publish version

    needs: [check_wheel]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install twine

      - name: Download wheel
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Publish to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish:
    name: Publish version
    if: |
      github.repository == 'soren-n/minigun-py' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    needs: [test_publish]
    runs-on: ubuntu-latest

    steps:
      - name: Download wheel
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}