name: Build and publish

on: [push, pull_request]

jobs:
  build_wheel:
    name: Build wheel

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheel
        run: uv build --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: ./dist/*.whl

  check_wheel:
    name: Check wheel

    needs: [build_wheel]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv pip install twine

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: ./dist

      - name: Test the wheel
        run: |
          find ./dist/*.whl -maxdepth 1 -type f | xargs uv pip install
          cd ..
          uv run python -c "import minigun, sys; print(minigun.__version__); sys.exit(0)"

      - name: Check README rendering for PyPI
        run: twine check dist/*

  test_publish:
    name: Test publish version

    needs: [check_wheel]
    runs-on: ubuntu-latest

    steps:
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: ./dist

      - name: Publish to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish:
    name: Publish version
    if: |
      github.repository == 'soren-n/minigun-py' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    needs: [test_publish]
    runs-on: ubuntu-latest

    steps:
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: ./dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}