name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.platform[1] }}

    runs-on: ${{ matrix.platform[0] }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - [ubuntu-20.04, manylinux_x86_64]
          - [windows-2019, win_amd64]
          - [macOS-12, macosx_*]
        python:
          - cp310
          - cp311

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir ./wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform[1] }}

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-${{ startsWith(matrix.platform[1], 'macosx') && 'macosx' || matrix.platform[1] }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Build sdist
        run: python setup.py sdist

      - name: Test the sdist
        run: |
          python -m pip install dist/*.gz
          python -m pip install -r requirements.txt
          cd ..
          python -c "import minigun, sys; print(minigun.__version__); sys.exit(0)"

      - name: Check README rendering for PyPI
        run: |
          python -m pip install twine
          twine check dist/*

      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: ./dist/*

  publish_all:
    name: Publish version
    if: >-
      github.repository == 'soren-n/minigun-py' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - name: Download wheels and sdist
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./dist

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}